-------------------------------------------------------------------------------
Test set: net.ausiasmarch.debesto.DebestoApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.729 s <<< FAILURE! - in net.ausiasmarch.debesto.DebestoApplicationTests
contextLoads  Time elapsed: 0.004 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: net.ausiasmarch.debesto.entity.UsuarioEntity.tipousuario in net.ausiasmarch.debesto.entity.TipoUsuarioEntity.usuarios
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: net.ausiasmarch.debesto.entity.UsuarioEntity.tipousuario in net.ausiasmarch.debesto.entity.TipoUsuarioEntity.usuarios

